import type {
    Recipe,
    UserInfo,
    RecipesByMeal,
    RecipeData,
    CountryOption,
    RefreshInterval,
} from "./Type";

// Recipe arrays
export const Recipes: Recipe[] = [];

export const MyRecipes: Recipe[] = [];

// Default user info template
export const DefaultUserInfo: UserInfo = {
    userName: "",
    firstName: "",
    lastName: "",
    email: "",
    password: "",
    country: "au",
    token: "",
};

// Recipe categories
const breakfastRecipes: Recipe[] = [];
const lunchRecipes: Recipe[] = [];
const dinnerRecipes: Recipe[] = [];
const snacksRecipes: Recipe[] = [];
const dessertRecipes: Recipe[] = [];

const recipes: RecipesByMeal = {
    breakfast: breakfastRecipes,
    lunch: lunchRecipes,
    dinner: dinnerRecipes,
    snacks: snacksRecipes,
    dessert: dessertRecipes,
};

export const defaultRecipeData: RecipeData = {
    data: recipes,
    lastRetrieval: "",
};

// Configuration constants
export const REFRESH_INTERVAL: RefreshInterval = 300; // seconds

// Country options for dropdown
export const CountryOptions: CountryOption[] = [
    { key: "af", value: "af", flag: "af", label: "Afghanistan" },
    { key: "ax", value: "ax", flag: "ax", label: "Aland Islands" },
    { key: "al", value: "al", flag: "al", label: "Albania" },
    { key: "dz", value: "dz", flag: "dz", label: "Algeria" },
    { key: "as", value: "as", flag: "as", label: "American Samoa" },
    { key: "ad", value: "ad", flag: "ad", label: "Andorra" },
    { key: "ao", value: "ao", flag: "ao", label: "Angola" },
    { key: "ai", value: "ai", flag: "ai", label: "Anguilla" },
    { key: "ag", value: "ag", flag: "ag", label: "Antigua" },
    { key: "ar", value: "ar", flag: "ar", label: "Argentina" },
    { key: "am", value: "am", flag: "am", label: "Armenia" },
    { key: "aw", value: "aw", flag: "aw", label: "Aruba" },
    { key: "au", value: "au", flag: "au", label: "Australia" },
    { key: "at", value: "at", flag: "at", label: "Austria" },
    { key: "az", value: "az", flag: "az", label: "Azerbaijan" },
    { key: "bs", value: "bs", flag: "bs", label: "Bahamas" },
    { key: "bh", value: "bh", flag: "bh", label: "Bahrain" },
    { key: "bd", value: "bd", flag: "bd", label: "Bangladesh" },
    { key: "bb", value: "bb", flag: "bb", label: "Barbados" },
    { key: "by", value: "by", flag: "by", label: "Belarus" },
    { key: "be", value: "be", flag: "be", label: "Belgium" },
    { key: "bz", value: "bz", flag: "bz", label: "Belize" },
    { key: "bj", value: "bj", flag: "bj", label: "Benin" },
    { key: "bm", value: "bm", flag: "bm", label: "Bermuda" },
    { key: "bt", value: "bt", flag: "bt", label: "Bhutan" },
    { key: "bo", value: "bo", flag: "bo", label: "Bolivia" },
    { key: "ba", value: "ba", flag: "ba", label: "Bosnia" },
    { key: "bw", value: "bw", flag: "bw", label: "Botswana" },
    { key: "bv", value: "bv", flag: "bv", label: "Bouvet Island" },
    { key: "br", value: "br", flag: "br", label: "Brazil" },
    { key: "vg", value: "vg", flag: "vg", label: "British Virgin Islands" },
    { key: "bn", value: "bn", flag: "bn", label: "Brunei" },
    { key: "bg", value: "bg", flag: "bg", label: "Bulgaria" },
    { key: "bf", value: "bf", flag: "bf", label: "Burkina Faso" },
    { key: "mm", value: "mm", flag: "mm", label: "Burma" },
    { key: "bi", value: "bi", flag: "bi", label: "Burundi" },
    { key: "tc", value: "tc", flag: "tc", label: "Caicos Islands" },
    { key: "kh", value: "kh", flag: "kh", label: "Cambodia" },
    { key: "cm", value: "cm", flag: "cm", label: "Cameroon" },
    { key: "ca", value: "ca", flag: "ca", label: "Canada" },
    { key: "cv", value: "cv", flag: "cv", label: "Cape Verde" },
    { key: "ky", value: "ky", flag: "ky", label: "Cayman Islands" },
    { key: "cf", value: "cf", flag: "cf", label: "Central African Republic" },
    { key: "td", value: "td", flag: "td", label: "Chad" },
    { key: "cl", value: "cl", flag: "cl", label: "Chile" },
    { key: "cn", value: "cn", flag: "cn", label: "China" },
    { key: "cx", value: "cx", flag: "cx", label: "Christmas Island" },
    { key: "cc", value: "cc", flag: "cc", label: "Cocos Islands" },
    { key: "co", value: "co", flag: "co", label: "Colombia" },
    { key: "km", value: "km", flag: "km", label: "Comoros" },
    { key: "cg", value: "cg", flag: "cg", label: "Congo Brazzaville" },
    { key: "cd", value: "cd", flag: "cd", label: "Congo" },
    { key: "ck", value: "ck", flag: "ck", label: "Cook Islands" },
    { key: "cr", value: "cr", flag: "cr", label: "Costa Rica" },
    { key: "ci", value: "ci", flag: "ci", label: "Cote Divoire" },
    { key: "hr", value: "hr", flag: "hr", label: "Croatia" },
    { key: "cu", value: "cu", flag: "cu", label: "Cuba" },
    { key: "cy", value: "cy", flag: "cy", label: "Cyprus" },
    { key: "cz", value: "cz", flag: "cz", label: "Czech Republic" },
    { key: "dk", value: "dk", flag: "dk", label: "Denmark" },
    { key: "dj", value: "dj", flag: "dj", label: "Djibouti" },
    { key: "dm", value: "dm", flag: "dm", label: "Dominica" },
    { key: "do", value: "do", flag: "do", label: "Dominican Republic" },
    { key: "ec", value: "ec", flag: "ec", label: "Ecuador" },
    { key: "eg", value: "eg", flag: "eg", label: "Egypt" },
    { key: "sv", value: "sv", flag: "sv", label: "El Salvador" },
    { key: "gb", value: "gb", flag: "gb", label: "England" },
    { key: "gq", value: "gq", flag: "gq", label: "Equatorial Guinea" },
    { key: "er", value: "er", flag: "er", label: "Eritrea" },
    { key: "ee", value: "ee", flag: "ee", label: "Estonia" },
    { key: "et", value: "et", flag: "et", label: "Ethiopia" },
    { key: "eu", value: "eu", flag: "eu", label: "European Union" },
    { key: "fk", value: "fk", flag: "fk", label: "Falkland Islands" },
    { key: "fo", value: "fo", flag: "fo", label: "Faroe Islands" },
    { key: "fj", value: "fj", flag: "fj", label: "Fiji" },
    { key: "fi", value: "fi", flag: "fi", label: "Finland" },
    { key: "fr", value: "fr", flag: "fr", label: "France" },
    { key: "gf", value: "gf", flag: "gf", label: "French Guiana" },
    { key: "pf", value: "pf", flag: "pf", label: "French Polynesia" },
    { key: "tf", value: "tf", flag: "tf", label: "French Territories" },
    { key: "ga", value: "ga", flag: "ga", label: "Gabon" },
    { key: "gm", value: "gm", flag: "gm", label: "Gambia" },
    { key: "ge", value: "ge", flag: "ge", label: "Georgia" },
    { key: "de", value: "de", flag: "de", label: "Germany" },
    { key: "gh", value: "gh", flag: "gh", label: "Ghana" },
    { key: "gi", value: "gi", flag: "gi", label: "Gibraltar" },
    { key: "gr", value: "gr", flag: "gr", label: "Greece" },
    { key: "gl", value: "gl", flag: "gl", label: "Greenland" },
    { key: "gd", value: "gd", flag: "gd", label: "Grenada" },
    { key: "gp", value: "gp", flag: "gp", label: "Guadeloupe" },
    { key: "gu", value: "gu", flag: "gu", label: "Guam" },
    { key: "gt", value: "gt", flag: "gt", label: "Guatemala" },
    { key: "gw", value: "gw", flag: "gw", label: "Guinea-Bissau" },
    { key: "gn", value: "gn", flag: "gn", label: "Guinea" },
    { key: "gy", value: "gy", flag: "gy", label: "Guyana" },
    { key: "ht", value: "ht", flag: "ht", label: "Haiti" },
    { key: "hm", value: "hm", flag: "hm", label: "Heard Island" },
    { key: "hn", value: "hn", flag: "hn", label: "Honduras" },
    { key: "hk", value: "hk", flag: "hk", label: "Hong Kong" },
    { key: "hu", value: "hu", flag: "hu", label: "Hungary" },
    { key: "is", value: "is", flag: "is", label: "Iceland" },
    { key: "in", value: "in", flag: "in", label: "India" },
    { key: "io", value: "io", flag: "io", label: "Indian Ocean Territory" },
    { key: "id", value: "id", flag: "id", label: "Indonesia" },
    { key: "ir", value: "ir", flag: "ir", label: "Iran" },
    { key: "iq", value: "iq", flag: "iq", label: "Iraq" },
    { key: "ie", value: "ie", flag: "ie", label: "Ireland" },
    { key: "il", value: "il", flag: "il", label: "Israel" },
    { key: "it", value: "it", flag: "it", label: "Italy" },
    { key: "jm", value: "jm", flag: "jm", label: "Jamaica" },
    { key: "jp", value: "jp", flag: "jp", label: "Japan" },
    { key: "jo", value: "jo", flag: "jo", label: "Jordan" },
    { key: "kz", value: "kz", flag: "kz", label: "Kazakhstan" },
    { key: "ke", value: "ke", flag: "ke", label: "Kenya" },
    { key: "ki", value: "ki", flag: "ki", label: "Kiribati" },
    { key: "kw", value: "kw", flag: "kw", label: "Kuwait" },
    { key: "kg", value: "kg", flag: "kg", label: "Kyrgyzstan" },
    { key: "la", value: "la", flag: "la", label: "Laos" },
    { key: "lv", value: "lv", flag: "lv", label: "Latvia" },
    { key: "lb", value: "lb", flag: "lb", label: "Lebanon" },
    { key: "ls", value: "ls", flag: "ls", label: "Lesotho" },
    { key: "lr", value: "lr", flag: "lr", label: "Liberia" },
    { key: "ly", value: "ly", flag: "ly", label: "Libya" },
    { key: "li", value: "li", flag: "li", label: "Liechtenstein" },
    { key: "lt", value: "lt", flag: "lt", label: "Lithuania" },
    { key: "lu", value: "lu", flag: "lu", label: "Luxembourg" },
    { key: "mo", value: "mo", flag: "mo", label: "Macau" },
    { key: "mk", value: "mk", flag: "mk", label: "Macedonia" },
    { key: "mg", value: "mg", flag: "mg", label: "Madagascar" },
    { key: "mw", value: "mw", flag: "mw", label: "Malawi" },
    { key: "my", value: "my", flag: "my", label: "Malaysia" },
    { key: "mv", value: "mv", flag: "mv", label: "Maldives" },
    { key: "ml", value: "ml", flag: "ml", label: "Mali" },
    { key: "mt", value: "mt", flag: "mt", label: "Malta" },
    { key: "mh", value: "mh", flag: "mh", label: "Marshall Islands" },
    { key: "mq", value: "mq", flag: "mq", label: "Martinique" },
    { key: "mr", value: "mr", flag: "mr", label: "Mauritania" },
    { key: "mu", value: "mu", flag: "mu", label: "Mauritius" },
    { key: "yt", value: "yt", flag: "yt", label: "Mayotte" },
    { key: "mx", value: "mx", flag: "mx", label: "Mexico" },
    { key: "fm", value: "fm", flag: "fm", label: "Micronesia" },
    { key: "md", value: "md", flag: "md", label: "Moldova" },
    { key: "mc", value: "mc", flag: "mc", label: "Monaco" },
    { key: "mn", value: "mn", flag: "mn", label: "Mongolia" },
    { key: "me", value: "me", flag: "me", label: "Montenegro" },
    { key: "ms", value: "ms", flag: "ms", label: "Montserrat" },
    { key: "ma", value: "ma", flag: "ma", label: "Morocco" },
    { key: "mz", value: "mz", flag: "mz", label: "Mozambique" },
    { key: "na", value: "na", flag: "na", label: "Namibia" },
    { key: "nr", value: "nr", flag: "nr", label: "Nauru" },
    { key: "np", value: "np", flag: "np", label: "Nepal" },
    { key: "an", value: "an", flag: "an", label: "Netherlands Antilles" },
    { key: "nl", value: "nl", flag: "nl", label: "Netherlands" },
    { key: "nc", value: "nc", flag: "nc", label: "New Caledonia" },
    { key: "pg", value: "pg", flag: "pg", label: "New Guinea" },
    { key: "nz", value: "nz", flag: "nz", label: "New Zealand" },
    { key: "ni", value: "ni", flag: "ni", label: "Nicaragua" },
    { key: "ne", value: "ne", flag: "ne", label: "Niger" },
    { key: "ng", value: "ng", flag: "ng", label: "Nigeria" },
    { key: "nu", value: "nu", flag: "nu", label: "Niue" },
    { key: "nf", value: "nf", flag: "nf", label: "Norfolk Island" },
    { key: "kp", value: "kp", flag: "kp", label: "North Korea" },
    { key: "mp", value: "mp", flag: "mp", label: "Northern Mariana Islands" },
    { key: "no", value: "no", flag: "no", label: "Norway" },
    { key: "om", value: "om", flag: "om", label: "Oman" },
    { key: "pk", value: "pk", flag: "pk", label: "Pakistan" },
    { key: "pw", value: "pw", flag: "pw", label: "Palau" },
    { key: "ps", value: "ps", flag: "ps", label: "Palestine" },
    { key: "pa", value: "pa", flag: "pa", label: "Panama" },
    { key: "py", value: "py", flag: "py", label: "Paraguay" },
    { key: "pe", value: "pe", flag: "pe", label: "Peru" },
    { key: "ph", value: "ph", flag: "ph", label: "Philippines" },
    { key: "pn", value: "pn", flag: "pn", label: "Pitcairn Islands" },
    { key: "pl", value: "pl", flag: "pl", label: "Poland" },
    { key: "pt", value: "pt", flag: "pt", label: "Portugal" },
    { key: "pr", value: "pr", flag: "pr", label: "Puerto Rico" },
    { key: "qa", value: "qa", flag: "qa", label: "Qatar" },
    { key: "re", value: "re", flag: "re", label: "Reunion" },
    { key: "ro", value: "ro", flag: "ro", label: "Romania" },
    { key: "ru", value: "ru", flag: "ru", label: "Russia" },
    { key: "rw", value: "rw", flag: "rw", label: "Rwanda" },
    { key: "sh", value: "sh", flag: "sh", label: "Saint Helena" },
    { key: "kn", value: "kn", flag: "kn", label: "Saint Kitts and Nevis" },
    { key: "lc", value: "lc", flag: "lc", label: "Saint Lucia" },
    { key: "pm", value: "pm", flag: "pm", label: "Saint Pierre" },
    { key: "vc", value: "vc", flag: "vc", label: "Saint Vincent" },
    { key: "ws", value: "ws", flag: "ws", label: "Samoa" },
    { key: "sm", value: "sm", flag: "sm", label: "San Marino" },
    { key: "gs", value: "gs", flag: "gs", label: "Sandwich Islands" },
    { key: "st", value: "st", flag: "st", label: "Sao Tome" },
    { key: "sa", value: "sa", flag: "sa", label: "Saudi Arabia" },
    { key: "sn", value: "sn", flag: "sn", label: "Senegal" },
    { key: "cs", value: "cs", flag: "cs", label: "Serbia" },
    { key: "rs", value: "rs", flag: "rs", label: "Serbia" },
    { key: "sc", value: "sc", flag: "sc", label: "Seychelles" },
    { key: "sl", value: "sl", flag: "sl", label: "Sierra Leone" },
    { key: "sg", value: "sg", flag: "sg", label: "Singapore" },
    { key: "sk", value: "sk", flag: "sk", label: "Slovakia" },
    { key: "si", value: "si", flag: "si", label: "Slovenia" },
    { key: "sb", value: "sb", flag: "sb", label: "Solomon Islands" },
    { key: "so", value: "so", flag: "so", label: "Somalia" },
    { key: "za", value: "za", flag: "za", label: "South Africa" },
    { key: "kr", value: "kr", flag: "kr", label: "South Korea" },
    { key: "es", value: "es", flag: "es", label: "Spain" },
    { key: "lk", value: "lk", flag: "lk", label: "Sri Lanka" },
    { key: "sd", value: "sd", flag: "sd", label: "Sudan" },
    { key: "sr", value: "sr", flag: "sr", label: "Suriname" },
    { key: "sj", value: "sj", flag: "sj", label: "Svalbard" },
    { key: "sz", value: "sz", flag: "sz", label: "Swaziland" },
    { key: "se", value: "se", flag: "se", label: "Sweden" },
    { key: "ch", value: "ch", flag: "ch", label: "Switzerland" },
    { key: "sy", value: "sy", flag: "sy", label: "Syria" },
    { key: "tw", value: "tw", flag: "tw", label: "Taiwan" },
    { key: "tj", value: "tj", flag: "tj", label: "Tajikistan" },
    { key: "tz", value: "tz", flag: "tz", label: "Tanzania" },
    { key: "th", value: "th", flag: "th", label: "Thailand" },
    { key: "tl", value: "tl", flag: "tl", label: "Timorleste" },
    { key: "tg", value: "tg", flag: "tg", label: "Togo" },
    { key: "tk", value: "tk", flag: "tk", label: "Tokelau" },
    { key: "to", value: "to", flag: "to", label: "Tonga" },
    { key: "tt", value: "tt", flag: "tt", label: "Trinidad" },
    { key: "tn", value: "tn", flag: "tn", label: "Tunisia" },
    { key: "tr", value: "tr", flag: "tr", label: "Turkey" },
    { key: "tm", value: "tm", flag: "tm", label: "Turkmenistan" },
    { key: "tv", value: "tv", flag: "tv", label: "Tuvalu" },
    { key: "ug", value: "ug", flag: "ug", label: "Uganda" },
    { key: "ua", value: "ua", flag: "ua", label: "Ukraine" },
    { key: "ae", value: "ae", flag: "ae", label: "United Arab Emirates" },
    { key: "us", value: "us", flag: "us", label: "United States" },
    { key: "uy", value: "uy", flag: "uy", label: "Uruguay" },
    { key: "um", value: "um", flag: "um", label: "Us Minor Islands" },
    { key: "vi", value: "vi", flag: "vi", label: "Us Virgin Islands" },
    { key: "uz", value: "uz", flag: "uz", label: "Uzbekistan" },
    { key: "vu", value: "vu", flag: "vu", label: "Vanuatu" },
    { key: "va", value: "va", flag: "va", label: "Vatican City" },
    { key: "ve", value: "ve", flag: "ve", label: "Venezuela" },
    { key: "vn", value: "vn", flag: "vn", label: "Vietnam" },
    { key: "wf", value: "wf", flag: "wf", label: "Wallis and Futuna" },
    { key: "eh", value: "eh", flag: "eh", label: "Western Sahara" },
    { key: "ye", value: "ye", flag: "ye", label: "Yemen" },
    { key: "zm", value: "zm", flag: "zm", label: "Zambia" },
    { key: "zw", value: "zw", flag: "zw", label: "Zimbabwe" },
];
